### ISSUE TITLE
Could you add a composer.json file to make including this library easier.

### ISSUE THREAD

**Issue by niel** [zeebinz/rarinfo#11]
Doesn't have to be full setup  on packagist, just the basics to allow installing with custom repo.
I'd be more the willing to do a PR for it.

**Comment by zeebinz** [comment]
Sure, submit a PR and I'll add it.

**Comment by niel** [comment]
Could you tag the commit with the latest version. I noticed you stopped tags after about 2.4?

**Comment by zeebinz** [comment]
Done - tagged and released as v2.5.0
