### ISSUE TITLE
Seeing a couple of RAR Info errors in PHP logs.

### ISSUE THREAD

**Issue by niel** [zeebinz/rarinfo#15]
Couple of notices show up occasionally.

PHP Notice:  Undefined offset: 1 in /var/www/nzedb/app/libraries/zeebinz/rarinfo/rarinfo.php on line 1030

PHP Notice:  Undefined index: method in /var/www/nzedb/app/libraries/zeebinz/rarinfo/rarinfo.php on line 687

The second one far more frequently, around 5:1

**Comment by zeebinz** [comment]
I can't emphasise enough how important sample files are when posting issues like this. It's easy enough to tweak the code to remove these notices, but without seeing a sample it's hard to diagnose the underlying issues correctly, or to know if a better fix is possible.

**Comment by niel** [comment]
I understand. If I'd had example RARs I would have provided them, but I found these errors while going through logs trying to diagnose another issue a couple days after they were generated, so the RARs were no longer available and no way to know what/which ones they were..
